#indent_style = "Block"
reorder_imports = true
max_width = 90
#imports_granularity = "Module"
#normalize_comments = true
#overflow_delimited_expr = true
#wrap_comments = true
use_try_shorthand = true
use_field_init_shorthand = true
single_line_if_else_max_width = 90
short_array_element_width_threshold = 10
match_block_trailing_comma = true
#binop_separator = "Back"
