CREATE TABLE files (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    hash VARCHAR(48) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    remotes TEXT NOT NULL,
    path VARCHAR(150) NOT NULL,
    size INTEGER,
    UNIQUE (hash),
    UNIQUE (id),
);

CREATE TABLE commits ( 
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    author VARCHAR(150) ,
    git_commit VARCHAR(150) ,
    message TEXT,
    timestamp INTEGER NOT NULL,
    file_from_id INTEGER NOT NULL,
    file_to_id INTEGER NOT NULL,
    diff_id INTEGER,
    UNIQUE (id),
    FOREIGN KEY (file_from_id) REFERENCES files(id),
    FOREIGN KEY (file_to_id) REFERENCES files(id),
    FOREIGN KEY (diff_id) REFERENCES diffs(id),
);

CREATE TABLE diffs ( 
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    git_commit VARCHAR(150) ,
    path VARCHAR(150) NOT NULL,
    UNIQUE (id),
);

CREATE TRIGGER update_files_timestamp
AFTER UPDATE ON files
FOR EACH ROW
BEGIN
    UPDATE files SET updated_at = CURRENT_TIMESTAMP WHERE id = NEW.id;
END;
