name: Build packages and create release

permissions:
  contents: write

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  CARGO_TERM_COLOR: always

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          prerelease: false
          draft: false
          make_latest: "true"

  build-exes:
    needs: build-exes
    strategy:
      matrix:
        features: [full, repro, notes]
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest    
          # - target: x86_64-apple-darwin
          #   os: macos-latest
          # - target: x86_64-pc-windows-msvc
          #   os: windows-latest

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: taiki
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          include: README.md
          leading-dir: true
          checksum: sha256
          archive: $bin-$tag-$target-${{ matrix.features }}
          features: ${{ matrix.features }}
          bin: yap
          target: ${{ matrix.target }}
          tar: unix
          zip: windows
          token: ${{ secrets.GITHUB_TOKEN }}